### ISSUE TITLE
Code for physical experiment

### ISSUE THREAD

**Issue by AnasASK** [maricante/ppSDF#1]
Thank you for the great project. I am interested in trying the physical experiment outlined in your paper which uses depth camera, is there a chance for providing the code for that?

**Comment by maricante** [comment]
Hi, thanks for taking interest!

I will look into adding the physical experiment code once I find a bit of time to clean it up. Likely within the next couple of weeks, because I am unfortunately a bit swamped currently...

Keep an eye on the new repository at [https://github.com/idiap/ppsdf](https://github.com/idiap/ppsdf), since I will probably be adding it there :)
